<!-- Page Header-->
<header class="masthead" style="background-image: url('assets/front/img/home-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>Clean Blog</h1>
                    <span class="subheading">A Blog Theme by Start Bootstrap</span>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Main Content-->
<main class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-12">
                <form class="d-flex justify-content-between" action="" method="get">
                    <input type="number" name="nb-post" placeholder="entrez le nombre d'articles souhaité"/>
                    <select class="form-select" name="post-tri" aria-label="Default select example"  style="max-width:33%">
                      <option value="DESC" >+ récent</option>
                      <option value="ASC">+ vieux</option>
                    </select>
                    <input type="submit" value="Submit"/>
                </form>
        </div>
        <div class="col-md-10 col-lg-8 col-xl-7">

            <!--On boucle sur le tableau d'articles pour créer les différents articles-->
            <?php foreach($posts as $post): ?>
                <!-- Post preview-->
                <div class="post-preview">
                    <a href="post.html">
                        <h2 class="post-title"><?php echo $post->getTitle(); ?></h2>
                        <h3 class="post-subtitle">Problems look mighty small from 150 miles up</h3>
                    </a>
                    <p class="post-meta">
                        Posted by
                        <a href="#!">Start Bootstrap</a>
                        on September 24, 2023
                    </p>
                </div>
                <!-- Divider-->
                <hr class="my-4" />
            
            <?php endforeach; ?>

            
            <!-- Pager-->
            <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="#!">Older Posts →</a></div>
        </div>
    </div>
</main>

